print(" _____________________")
print("|    Engine Name:     |")
print("|                     |")
print("|    Starry Night     |")
print("|                     |")
print("|    ID:515644515     |")
print("|                     |")
print("|    Version 0.15     |")
print("|                     |")
print("|       Made By       |")
print("|                     |")
print("|     DalostNight     |")
print("|                     |")
print("|     Engineinfo:     |")
print("|_____________________|")